In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('all_spectra_row_v1.csv', index_col=0)

In [3]:
df.groupby('label').count()

,399.2094,401.138,403.0665,404.9951,406.9236,408.8522,410.7807,412.7093,414.6378,416.5664,...,3984.38,3986.309,3988.237,3990.1659999999997,3992.094,3994.0229999999997,3995.9509999999996,3997.88,3999.809,4001.737
label,,,,,,,,,,,,,,,,,,,,,
1.10,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
1.11,0,0,0,0,0,0,0,0,0,0,...,52,52,52,52,52,52,52,52,52,0
1.50,0,0,0,0,0,0,0,0,0,0,...,44,44,44,44,44,44,44,44,44,0
1.60,0,0,0,0,0,0,0,0,0,0,...,40,40,40,40,40,40,40,40,40,0
1.90,0,0,0,0,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,24,0
2.10,0,0,0,0,0,0,0,0,0,0,...,35,35,35,35,35,35,35,35,35,0
2.30,0,0,0,0,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,16,0
3.10,0,0,0,0,0,0,0,0,0,0,...,33,33,33,33,33,33,33,33,33,0
3.11,0,0,0,0,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,22,0
3.12,0,0,0,0,0,0,0,0,0,0,...,15,15,15,15,15,15,15,15,15,0
3.20,0,0,0,0,0,0,0,0,0,0,...,18,18,18,18,18,18,18,18,18,0
3.50,0,0,0,0,0,0,0,0,0,0,...,44,44,44,44,44,44,44,44,44,0

In [5]:
## Creating cases with each label with 30 instances in each

## Has alreay 30 instances
cases_11 = df[df['label'] == 1.1]

# 30 instances will remain in the training set, rest will go to the test set
cases_111 = df[df['label'] == 1.11][:30]
cases_111_test = df[df['label'] == 1.11][30:]

# 30 instances will remain in the training set, rest will go to the test set
cases_15 = df[df['label'] == 1.5][:30]
cases_15_test = df[df['label'] == 1.5][30:]

# 30 instances will remain in the training set, rest will go to the test set
cases_16 = df[df['label'] == 1.6][:30]
cases_16_test = df[df['label'] == 1.6][30:]

# To get 30 instances the missing amount is produced by duplicating the existing instances
cases_19 = df[df['label'] == 1.9]
cases_19 = pd.concat([cases_19, cases_19[:30 - len(cases_19.index)]])

# 30 instances will remain in the training set, rest will go to the test set
cases_21 = df[df['label'] == 2.1][:30]
cases_21_test = df[df['label'] == 2.1][30:]

# To get 30 instances the missing amount is produced by duplicating the existing instances
cases_23 = df[df['label'] == 2.3]
cases_23 = pd.concat([cases_23, cases_23[:30 - len(cases_23.index)]])

# 30 instances will remain in the training set, rest will go to the test set
cases_31 = df[df['label'] == 3.1][:30]
cases_31_test = df[df['label'] == 3.1][30:]

# To get 30 instances the missing amount is produced by duplicating the existing instances
cases_311 = df[df['label'] == 3.11]
cases_311 = pd.concat([cases_311, cases_311[:30 - len(cases_311.index)]])

# To get 30 instances the missing amount is produced by duplicating the existing instances
cases_312 = df[df['label'] == 3.12]
cases_312 = pd.concat([cases_312, cases_312[:30 - len(cases_312.index)]])

# To get 30 instances the missing amount is produced by duplicating the existing instances
cases_32 = df[df['label'] == 3.2]
cases_32 = pd.concat([cases_32, cases_32[:30 - len(cases_32.index)]])

# 30 instances will remain in the training set, rest will go to the test set
cases_35 = df[df['label'] == 3.5][:30]
cases_35_test = df[df['label'] == 3.5][30:]


df_train = pd.concat([cases_11, cases_111, cases_15, cases_16, cases_19, cases_21, cases_23, cases_31, cases_311, cases_312, cases_32, cases_35])
df_test = pd.concat([cases_111_test, cases_15_test, cases_16_test, cases_21_test, cases_31_test, cases_35_test])

## Writing to csv
df_train.to_csv('spectra_balanced.csv')
df_test.to_csv('spectra_test.csv')

In [6]:
df_train.groupby('label').count()

,399.2094,401.138,403.0665,404.9951,406.9236,408.8522,410.7807,412.7093,414.6378,416.5664,...,3984.38,3986.309,3988.237,3990.1659999999997,3992.094,3994.0229999999997,3995.9509999999996,3997.88,3999.809,4001.737
label,,,,,,,,,,,,,,,,,,,,,
1.10,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
1.11,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
1.50,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
1.60,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
1.90,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
2.10,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
2.30,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
3.10,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
3.11,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
3.12,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
3.20,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0
3.50,0,0,0,0,0,0,0,0,0,0,...,30,30,30,30,30,30,30,30,30,0